name: Build

on:
  workflow_dispatch:
  push:

jobs:
    lint:
      name: Lint
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-contrib/golangci-lint@v1
          env:
            GO111MODULE: "on"
            GOFLAGS: "-mod=vendor"

    test:
      name: Unit tests
      runs-on: ubuntu-20.04
      steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16

        - name: Checkout codebase
          uses: actions/checkout@v2

        - name: Run unit tests
          run: go test ./...

