name: Build

on:
  workflow_dispatch:
  push:

jobs:
    lint:
      name: Lint
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-contrib/golangci-lint@v1
          env:
            GO111MODULE: "on"
            GOFLAGS: "-mod=vendor"

    test:
      name: Unit tests
      runs-on: ubuntu-20.04
      steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16

        - name: Checkout codebase
          uses: actions/checkout@v2

        - name: Run unit tests
          run: go test ./...

    image:
      name: Build Docker image
      runs-on: ubuntu-20.04
      env:
        HASH: $(git rev-parse --short "$GITHUB_SHA")
        BRANCH: ${GITHUB_REF##*/}
        IMAGE_NAME: ${{ secrets.SERVICE_NAME }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      steps:
        - name: Checkout codebase
          uses: actions/checkout@v2

        - name: Setup gcloud
          uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
            project_id: ${{ secrets.PROJECT_ID }}
            export_default_credentials: true

        - run: |
            gcloud auth configure-docker -q

        - name: Image
          run: |-
            docker build --build-arg -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .
