name: Build

on:
  workflow_dispatch:
  push:

jobs:
    lint:
      name: Lint
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-contrib/golangci-lint@v1
          env:
            GO111MODULE: "on"
            GOFLAGS: "-mod=vendor"
